name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your build steps here
      - name: Check formatting
        uses: khulnasoft/workflows/.github/workflows/lint.yml@master
